install.sh: use libmamba solver instead of mamba
Was getting:

```
mamba env create -p /miniconda/envs/umccrise --file umccrise/envs/umccrise.yml
[0m[91mTraceback (most recent call last):
File "/miniconda/bin/mamba", line 7, in <module>
from mamba.mamba import main
File "/miniconda/lib/python3.11/site-packages/mamba/mamba.py", line 49, in <module>
import libmambapy as api
File "/miniconda/lib/python3.11/site-packages/libmambapy/__init__.py", line 7, in <module>
raise e
File "/miniconda/lib/python3.11/site-packages/libmambapy/__init__.py", line 4, in <module>
from libmambapy.bindings import *  # noqa: F401,F403
ImportError: libarchive.so.13: cannot open shared object file: No such file or directory
The command '/bin/sh -c /bin/bash -xe umccrise/install.sh && rm load_umccrise.sh' returned a non-zero code: 1
```